title = "A Blog"
languageCode = "en-us"
baseurl = "https://sjp38.github.io/"
paginate = "10"
theme = "mainroad"


[Author]
    name = "SeongJae Park"
    bio = "A f/oss hacker"
    avatar = "img/avatar.png"


[Params]
    subtitle = "A blog for miscellaneous things"
    description = "This is a blog of SeongJae Park for miscellaneous things."
    opengraph = true
    leftsidebar = false
    authorbox = true
    post_navigation = true


[Params.widgets]
    search = true
    recent_articles = true
    categories = true
    tags = true
