title = "Happy Hacking"
languageCode = "en-us"
baseurl = "https://sjp38.github.io/"
paginate = "5"
theme = "beautifulhugo"
googleAnalytics = "UA-30621335-1"


[Author]
    name = "SeongJae Park"
    bio = "A f/oss hacker"
    avatar = "img/avatar.png"
    email = "sj38.park@gmail.com"
    github = "sjp38"
    linkedin = "seongjae-park-1a5b9954"


[Params]
    subtitle = "Let the hacking begin"
    description = "This is a blog of SeongJae Park for miscellaneous things."
    opengraph = true
    leftsidebar = false
    authorbox = true
    post_navigation = true
    logo = "img/tux.png"


[Params.widgets]
    search = true
    recent_articles = true
    categories = true
    tags = true

[[menu.main]]
    url = "/categories/projects"
    name = "Projects"
    weight = 1

[[menu.main]]
    url = "/categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    url = "/tags"
    name = "Tags"
    weight = 1
